language: python
sudo: false

env:
      global:
        - secure: "TYl+aEVdJGNWHCLhxtTrESre2qTJBI0iJpzzlsKKEcl9Patl3o4CUITweONpPPbeNF5aNRwsWrrgv4iIy8T5ND/AxUldSNbXmE9S35ZjvIYTbcmqXC9eYWjhLXMoWbdFxUORoybw9W/d+RgXrkkdL2GmrEbAAxasB3//Mqq3Nsii5jDssXtmZSXhxoj3TvKhzlklYopXfLYNeFsBcvGfkQ0mIvGNIMxECkFv5MIxpDKj0i9qQF/m8PSmECIeje7ZDPPXA7Si1SJyEo2w/FxD9LmMFg1ZW5YmLxsQtRxW6u6PxwxJmyNeLjgc9l/I+hy0oPo6gvva9te8FbUuQ9B2JYOvK5r4VEIZFfingoRMiMmWie89uSMxHHzgAsC3bl77dF5H24qTbXO6rSW3K5XEMVjxGEzTO+EW0Q4TC+329OaTzxJiQ2UtxOh66TXRIJ0NauSIcH367VeO8zHN977RT0QmSkTSAxUM3Ocdwy51qFEFnZS7Npw9BQ8tmgypC/ocpbLhkZWkVQ3auoNJMkjUvThbVwTBdexsyxxLvjAFUcrCh3A3HjC4fZ9GSXmnYo945+7UIO5jU7ssbVC+fovvduYa/6DRzSPAQ/Uw7p6Kw9zCMR3yPJaiWMfg8gTXY4YZS2PXAkL+Iy6ZgIOM5j6dVFaOd5gOgAnxl7miR1YsGz8="

env:
  global:
    - PIP_DEPS="flake8 pytest coveralls pytest-cov"

python:
- '2.7'
- '3.6'

install:
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /doc/`
- py.test --pyargs keratin --cov-report term-missing --cov=keratin

after_success:
- coveralls
- |
    if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
      pip install sphinx sphinx-gallery pillow
      # Doctr for gh-pages;
      set -e;
      pip install doctr;
      cd doc;
      make html;
      cd ..;
      doctr deploy . --built-docs doc/_build/html --no-require-master;
    fi
