language: python
sudo: false

env:
      global:
        - secure: "RCb5YIbA2hzraOuElWFi46rPIRKTpx53uYtDAAJMSnFfQoLo8kTkWq09wnDZ80RsIxzbao3A7rnupbfofcludruBSZhSMIsEku/lPgVY58FGpPKzX3036c6nG5mqGvuRLppfnMJTGocZzf49MBlCswGOZnosyLTIm/vbL41vKAvVCk4Udtqpn/m5OlDb72ORfz1g5twvvQULF+6TYrc2PYgkWyHFI2+VOROES45C88plllfaeLks+RTyQWxpmkD4V7KX26pi0NKxKjKxxcw/Sfqq1+ZpSy6SsTrVyKvnjXZLbuGoGTsoNmQNIq+ln7a9pfg3Fjr7cvZejpCwTuBDtPxmyWTsTR/F+SpIfcLx2hib8NYBRhBGXhhFYu7xjQNnSB30X41iNKjQDYx0oL3Hzo2zubjfbzPnOVwLJXSk6yZMhNpFrggPLJsQVGXH82204adSLbdHa5Ik0DUrxabOajiJ5FarfuJmynqSW4FMvBCZCfKNPajPKo2lpV8FhhtJtxoWE70SDZp5JrRE16ULWVEEcS6STCK+jG34bbQcAHrw/ikFRASQkhyaO86L82EuVhIUOAanrSVPx/zKU8IVqEvajdRSFGyu22XKsbvSr/zRawer0GQtJjg4Q8ZVBkO/h5bIakpHuep5Kgw20Y3B7Gbiju+CcWHscA0lHkKNg3U="


env:
  global:
    - PIP_DEPS="flake8 pytest coveralls pytest-cov"

python:
- '2.7'
- '3.6'

install:
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /doc/`
- py.test --pyargs keratin --cov-report term-missing --cov=keratin

after_success:
- coveralls
- |
    if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
      pip install sphinx sphinx-gallery pillow
      # Doctr for gh-pages;
      set -e;
      pip install doctr;
      cd doc;
      make html;
      cd ..;
      doctr deploy . --built-docs doc/_build/html --no-require-master;
    fi
